version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.1.0
  # https://circleci.com/developer/orbs/orb/circleci/aws-ecr
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    docker:
       - image: cimg/node:16.10
       - image: mongo:4.2.0
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        command: npm test
        name: Run Mocha tests   
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results   
    environment:
       - ECR_REPO_URL: "148774211651.dkr.ecr.us-east-1.amazonaws.com"
       - run: echo "ECR repo URL is $ECR_REPO_URL"    

workflows:
  node-tests:
    jobs:
      - build
      #Envs: AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
      - aws-ecr/build-and-push-image:
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: build/Dockerfile.prod
          #repository-url: "${148774211651}.dkr.ecr.${us-east-1}.amazonaws.com"
          repo: mahira
          requires:
                - build
